/**
 * Generates the occupant index from registry.json, so registering an
 * occupant is one registry item and nothing else.
 *
 * Every item with meta.layer "occupant" must have, in registry/<name>/:
 *   <name>.occupant.ts    exporting its spec, as <camelName>Occupant
 *   <name>.tsx            exporting its component, as <PascalName>
 *   examples/index.ts     exporting EXAMPLES, its example views by role:
 *                         primary, secondary, and stress (not shipped)
 *
 * Every item with meta.layer "surface" must have registry/<name>/<name>.surface.ts
 * exporting its spec as <camelName>Surface.
 *
 * It writes two committed files:
 *   lib/occupants.generated.ts          occupant specs and example names, and
 *                                       surface specs (no React), for docs
 *                                       and tests
 *   lib/occupant-registry.generated.tsx specs, components, and examples,
 *                                       for previews and the check fixture
 *
 * With --check, nothing is written; it fails if either file is stale. It
 * runs as part of `lint`.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { camel, namesIn, pascal, readRegistry, root } from "./lib.ts";

const checkOnly = process.argv.includes("--check");

const items = readRegistry();
const occupants = namesIn(items, "occupant").toSorted();
const surfaces = namesIn(items, "surface").toSorted();

const problems: string[] = [];
for (const name of surfaces) {
  const spec = `registry/${name}/${name}.surface.ts`;
  if (
    !existsSync(join(root, spec)) ||
    !readFileSync(join(root, spec), "utf8").includes(`${camel(name)}Surface`)
  ) {
    problems.push(`${name}: ${spec} must export ${camel(name)}Surface`);
  }
}
for (const name of occupants) {
  const dir = `registry/${name}`;
  const spec = `${dir}/${name}.occupant.ts`;
  const component = `${dir}/${name}.tsx`;
  const examples = `${dir}/examples/index.ts`;
  for (const file of [spec, component, examples]) {
    if (!existsSync(join(root, file)))
      problems.push(`${name}: missing ${file}`);
  }
  if (
    existsSync(join(root, spec)) &&
    !readFileSync(join(root, spec), "utf8").includes(
      `export const ${camel(name)}Occupant`,
    )
  ) {
    problems.push(`${name}: ${spec} must export ${camel(name)}Occupant`);
  }
  if (existsSync(join(root, examples))) {
    const source = readFileSync(join(root, examples), "utf8");
    for (const role of ["primary", "secondary", "stress"]) {
      if (!new RegExp(`\\b${role}:`).test(source)) {
        problems.push(`${name}: ${examples} needs a "${role}" example`);
      }
    }
  }
}
if (problems.length) {
  console.error(`Occupant index: ${problems.join("\n  ")}`);
  process.exit(1);
}

const HEADER =
  "// Generated by `pnpm generate:occupants` from registry.json. Don't edit;\n" +
  "// add an occupant item to the registry and rerun it.\n";

const specsTs = `${HEADER}
import type { OccupantSpec, SurfaceSpec } from "@/lib/composition";
${surfaces.map((name) => `import { ${camel(name)}Surface } from "@/registry/${name}/${name}.surface";`).join("\n")}
${occupants
  .map(
    (name) =>
      `import { ${camel(name)}Occupant } from "@/registry/${name}/${name}.occupant";\nimport { EXAMPLES as ${camel(name)}Examples } from "@/registry/${name}/examples";`,
  )
  .join("\n")}

export interface RegisteredOccupantSpec {
  spec: OccupantSpec;
  /** Its example roles: primary, secondary, and stress. */
  examples: readonly string[];
}

/** Every registered surface. */
export const SURFACE_SPECS: readonly SurfaceSpec[] = [
${surfaces.map((name) => `  ${camel(name)}Surface,`).join("\n")}
];

/** Every registered occupant, by name. */
export const OCCUPANT_SPECS: readonly RegisteredOccupantSpec[] = [
${occupants
  .map(
    (name) =>
      `  { spec: ${camel(name)}Occupant, examples: Object.keys(${camel(name)}Examples) },`,
  )
  .join("\n")}
];
`;

const registryTsx = `${HEADER}
import { defineOccupant, type RegisteredOccupant } from "@/lib/occupant-entry";
${occupants
  .map(
    (name) =>
      `import { ${pascal(name)} } from "@/registry/${name}/${name}";\nimport { ${camel(name)}Occupant } from "@/registry/${name}/${name}.occupant";\nimport { EXAMPLES as ${camel(name)}Examples } from "@/registry/${name}/examples";`,
  )
  .join("\n")}

/** Every registered occupant with its component and example views. */
export const OCCUPANT_REGISTRY: readonly RegisteredOccupant[] = [
${occupants
  .map(
    (name) =>
      `  defineOccupant({ spec: ${camel(name)}Occupant, Component: ${pascal(name)}, examples: ${camel(name)}Examples }),`,
  )
  .join("\n")}
];
`;

// Format through a real file next to the output: Biome's stdin mode doesn't
// apply this app's nested config, so it would disagree with format:check.
const biome = join(root, "node_modules/.bin/biome");
const format = (path: string, source: string) => {
  const scratch = path.replace(/(\.tsx?)$/, ".formatting$1");
  writeFileSync(join(root, scratch), source);
  try {
    execFileSync(biome, ["format", "--write", scratch], {
      cwd: root,
      stdio: "ignore",
    });
    return readFileSync(join(root, scratch), "utf8");
  } finally {
    rmSync(join(root, scratch), { force: true });
  }
};

const outputs: [string, string][] = [
  ["lib/occupants.generated.ts", format("lib/occupants.generated.ts", specsTs)],
  [
    "lib/occupant-registry.generated.tsx",
    format("lib/occupant-registry.generated.tsx", registryTsx),
  ],
];

if (checkOnly) {
  const stale = outputs.filter(
    ([path, content]) =>
      !existsSync(join(root, path)) ||
      readFileSync(join(root, path), "utf8") !== content,
  );
  if (stale.length) {
    console.error(
      `Stale: ${stale.map(([path]) => path).join(", ")}. Run \`pnpm generate:occupants\`.`,
    );
    process.exit(1);
  }
  console.log(`Occupant index is up to date (${occupants.length} occupants).`);
} else {
  for (const [path, content] of outputs)
    writeFileSync(join(root, path), content);
  console.log(`Wrote the occupant index: ${occupants.join(", ")}.`);
}
