// Generated by scripts/generate-theme-css.ts from registry.json. Do not edit.
// Change the tokens in registry.json and run `pnpm generate:theme`;
// `pnpm lint` fails while this file is out of date.

/** Layout tokens from the apollo-vertex-theme item, in px. */
export const LAYOUT_TOKENS = {
  surfaceInset: 24,
  sidePanelWidthMin: 280,
  contentAreaWidthMin: 480,
  scrollFadeSize: 24,
  slotDividerWidth: 1,
} as const;

/** The --sidebar strength in --side-panel-tint, as a percentage. */
export const SIDE_PANEL_TINT_STRENGTH = 60;

/** --panel-transition-duration, in ms. */
export const PANEL_TRANSITION_DURATION_MS = 350;
