export default {
  index: { display: "hidden" },
  overview: "Overview",
  accordion: "Accordion",
  alert: "Alert",
  "alert-dialog": "Alert Dialog",
  "aspect-ratio": "Aspect Ratio",
  avatar: "Avatar",
  badge: "Badge",
  breadcrumb: "Breadcrumb",
  button: "Button",
  "button-group": "Button Group",
  calendar: "Calendar",
  card: "Card",
  carousel: "Carousel",
  chart: "Chart",
  "line-chart": "Line Chart",
  "multi-line-chart": "Multi-Line Chart",
  "bar-chart": "Bar Chart",
  "distribution-chart": "Distribution Chart",
  "kpi-chart": "KPI Chart",
  "table-chart": "Table Chart",
  checkbox: "Checkbox",
  collapsible: "Collapsible",
  combobox: "Combobox",
  command: "Command",
  "context-menu": "Context Menu",
  "data-table": "Data Table",
  "date-picker": "Date Picker",
  dialog: "Dialog",
  drawer: "Drawer",
  "dropdown-menu": "Dropdown Menu",
  empty: "Empty",
  field: "Field",
  "feature-flags": "Feature Flags",
  "filter-dropdown": "Filter Dropdown",
  form: "Form",
  "form-wizard": "Form Wizard",
  "hover-card": "Hover Card",
  input: "Input",
  "input-group": "Input Group",
  "input-otp": "Input OTP",
  item: "Item",
  kbd: "Kbd",
  label: "Label",
  menubar: "Menubar",
  "navigation-menu": "Navigation Menu",
  pagination: "Pagination",
  popover: "Popover",
  progress: "Progress",
  "radio-group": "Radio Group",
  resizable: "Resizable",
  "scroll-area": "Scroll Area",
  select: "Select",
  separator: "Separator",
  sheet: "Sheet",
  sidebar: "Sidebar",
  skeleton: "Skeleton",
  slider: "Slider",
  sonner: "Sonner",
  spinner: "Spinner",
  switch: "Switch",
  table: "Table",
  tabs: "Tabs",
  textarea: "Textarea",
  toggle: "Toggle",
  "toggle-group": "Toggle Group",
  tooltip: "Tooltip",
};
