import type { EnrichedGuardrailDefinition } from '../definitions-enrich';

/**
 * Golden output of enrichment over the six built-ins and the three bring-your-own fixtures,
 * with no translator supplied and nothing hidden.
 *
 * A typed module rather than a file snapshot, deliberately: the repo has no snapshot precedent,
 * and biome formats every file it can parse, so a written snapshot would be reformatted on the
 * next check and then fail against itself. This is type-checked, biome-stable, and reviewable as
 * a diff, which is what a golden is for.
 *
 * Regenerate only when a change to the layer is intended, and read the diff as that change’s
 * user-visible summary: every label, tooltip, option label and numeric bound the two products
 * render is in here.
 */
export const GOLDEN_ENRICHED_DEFINITIONS: EnrichedGuardrailDefinition[] = [
  {
    validator: 'pii_detection',
    displayName: 'PII detection',
    allowedScopes: ['Agent', 'Llm', 'Tool'],
    parameters: [
      {
        id: 'entities',
        type: 'enum-list',
        label: 'Entities to detect',
        required: true,
        defaultValue: ['Email', 'Address'],
        options: [
          'Person',
          'Address',
          'Date',
          'PhoneNumber',
          'EugpsCoordinates',
          'Email',
          'CreditCardNumber',
          'InternationalBankingAccountNumber',
          'SwiftCode',
          'ABARoutingNumber',
          'USDriversLicenseNumber',
          'UKDriversLicenseNumber',
          'USIndividualTaxpayerIdentification',
          'UKUniqueTaxpayerNumber',
          'USBankAccountNumber',
          'USSocialSecurityNumber',
          'UsukPassportNumber',
          'URL',
          'IPAddress',
          'NOIdentityNumber',
          'FINationalID',
          'FIPassportNumber',
          'SENationalID',
          'DKPersonalIdentificationNumber',
          'NLCitizensServiceNumber',
        ],
        optionLabels: {
          Person: 'Person',
          Address: 'Address',
          Date: 'Date',
          PhoneNumber: 'Phone Number',
          EugpsCoordinates: 'EU GPS Coordinates',
          Email: 'Email',
          CreditCardNumber: 'Credit Card Number',
          InternationalBankingAccountNumber: 'International Banking Account Number (IBAN)',
          SwiftCode: 'SWIFT Code',
          ABARoutingNumber: 'ABA Routing Number',
          USDriversLicenseNumber: "US Driver's License Number",
          UKDriversLicenseNumber: "UK Driver's License Number",
          USIndividualTaxpayerIdentification: 'US Individual Taxpayer Identification Number (ITIN)',
          UKUniqueTaxpayerNumber: 'UK Unique Taxpayer Number (UTR)',
          USBankAccountNumber: 'US Bank Account Number',
          USSocialSecurityNumber: 'US Social Security Number (SSN)',
          UsukPassportNumber: 'US/UK Passport Number',
          NOIdentityNumber: 'Norway Identity Number',
          FINationalID: 'Finland National ID',
          FIPassportNumber: 'Finland Passport Number',
          SENationalID: 'Sweden National ID',
          DKPersonalIdentificationNumber: 'Danish Personal Identification Number',
          NLCitizensServiceNumber: 'Netherlands Citizens Service Number',
          URL: 'URL',
          IPAddress: 'IP Address',
        },
      },
      {
        id: 'entityThresholds',
        type: 'map-enum',
        label: 'Detection thresholds',
        required: true,
        defaultValue: {
          Person: 0.5,
          Address: 0.5,
          Date: 0.5,
          PhoneNumber: 0.5,
          EugpsCoordinates: 0.5,
          Email: 0.5,
          CreditCardNumber: 0.5,
          InternationalBankingAccountNumber: 0.5,
          SwiftCode: 0.5,
          ABARoutingNumber: 0.5,
          USDriversLicenseNumber: 0.5,
          UKDriversLicenseNumber: 0.5,
          USIndividualTaxpayerIdentification: 0.5,
          UKUniqueTaxpayerNumber: 0.5,
          USBankAccountNumber: 0.5,
          USSocialSecurityNumber: 0.5,
          UsukPassportNumber: 0.5,
          URL: 0.5,
          IPAddress: 0.5,
          NOIdentityNumber: 0.5,
          FINationalID: 0.5,
          FIPassportNumber: 0.5,
          SENationalID: 0.5,
          DKPersonalIdentificationNumber: 0.5,
          NLCitizensServiceNumber: 0.5,
        },
        tooltip:
          'Value between 0 and 1. The sensitivity level for PII detection. Higher thresholds detect more potential PII but may result in more false positives.',
        keySource: 'entities',
        min: 0,
        max: 1,
        step: 0.1,
      },
    ],
    status: 'Available',
    description: 'Detect personally identifiable information using Azure Cognitive Services.',
    guardrailStages: {
      Agent: ['PreExecution', 'PostExecution'],
      Llm: ['PreExecution', 'PostExecution'],
      Tool: ['PreExecution', 'PostExecution'],
    },
    isByogSubscription: false,
  },
  {
    validator: 'prompt_injection',
    displayName: 'Prompt injection',
    allowedScopes: ['Llm'],
    parameters: [
      {
        id: 'threshold',
        type: 'number',
        label: 'Detection threshold',
        required: false,
        defaultValue: 0.5,
        tooltip:
          'Value between 0 and 1. The sensitivity level for Prompt Injection detection. Higher thresholds detect more potential Prompt Injection but may result in more false positives.',
        min: 0,
        max: 1,
        step: 0.1,
      },
    ],
    status: 'Available',
    description:
      'This validator is provided by Noma Security and is built to detect malicious attack attempts (e.g. prompt injection, jailbreak) in LLM calls.',
    guardrailStages: {
      Llm: ['PreExecution'],
    },
    isByogSubscription: false,
  },
  {
    validator: 'harmful_content',
    displayName: 'Harmful content',
    allowedScopes: ['Agent', 'Llm', 'Tool'],
    parameters: [
      {
        id: 'harmfulContentEntities',
        type: 'enum-list',
        label: 'Content categories',
        required: true,
        defaultValue: ['Hate', 'SelfHarm'],
        options: ['Hate', 'SelfHarm', 'Sexual', 'Violence'],
        optionLabels: {
          Hate: 'Hate',
          SelfHarm: 'Self-harm',
          Sexual: 'Sexual',
          Violence: 'Violence',
        },
      },
      {
        id: 'harmfulContentEntityThresholds',
        type: 'map-enum',
        label: 'Severity thresholds',
        required: true,
        defaultValue: {
          Hate: 2,
          SelfHarm: 2,
          Sexual: 2,
          Violence: 2,
        },
        tooltip:
          'Integer value between 0 and 6 (step 2). The severity threshold for harmful content detection. Higher values require more severe content before triggering.',
        keySource: 'harmfulContentEntities',
        min: 0,
        max: 6,
        step: 2,
      },
    ],
    status: 'Available',
    description: 'Detect harmful content (e.g. hate, violence) using Azure AI Content Safety.',
    guardrailStages: {
      Agent: ['PreExecution', 'PostExecution'],
      Llm: ['PreExecution', 'PostExecution'],
      Tool: ['PreExecution', 'PostExecution'],
    },
    payloadMaxSizeLimit: 10000,
    isByogSubscription: false,
  },
  {
    validator: 'intellectual_property',
    displayName: 'Intellectual property',
    allowedScopes: ['Llm', 'Agent'],
    parameters: [
      {
        id: 'ipEntities',
        type: 'enum-list',
        label: 'Content types',
        required: true,
        defaultValue: ['Text'],
        options: ['Text', 'Code'],
        optionLabels: {
          Text: 'Text',
          Code: 'Code',
        },
      },
    ],
    status: 'Available',
    description:
      'Detect potential intellectual property violations in text and code using Azure AI Content Safety.',
    guardrailStages: {
      Llm: ['PostExecution'],
      Agent: ['PostExecution'],
    },
    payloadMinSizeLimit: 111,
    payloadMaxSizeLimit: 10000,
    isByogSubscription: false,
  },
  {
    validator: 'user_prompt_attacks',
    displayName: 'User prompt attacks',
    allowedScopes: ['Llm'],
    parameters: [],
    status: 'Available',
    description:
      'Detect user prompt attacks that attempt to bypass system instructions using Azure AI Content Safety.',
    guardrailStages: {
      Llm: ['PreExecution'],
    },
    payloadMaxSizeLimit: 10000,
    isByogSubscription: false,
  },
  {
    validator: 'llm_as_judge',
    displayName: 'LLM as Judge',
    allowedScopes: ['Agent', 'Llm', 'Tool'],
    parameters: [
      {
        id: 'guardrailText',
        type: 'text',
        label: 'Rule prompt',
        required: true,
        defaultValue: '',
        tooltip:
          'Describe the rule the judge will enforce. Be specific about what should pass and what should fail.',
        maxLength: 4000,
      },
      {
        id: 'model',
        type: 'enum',
        label: 'Judge model',
        required: true,
        defaultValue: '',
        tooltip: 'The model used to evaluate the policy against each payload.',
        options: [],
      },
      {
        id: 'positiveExamples',
        type: 'text-list',
        label: 'Positive examples',
        required: false,
        defaultValue: [],
        tooltip:
          'Optional payloads that should pass the policy. Used by the judge as calibration anchors.',
        maxLength: 1000,
        maxItems: 2,
      },
      {
        id: 'negativeExamples',
        type: 'text-list',
        label: 'Negative examples',
        required: false,
        defaultValue: [],
        tooltip:
          'Optional payloads that should fail the policy. Used by the judge as calibration anchors.',
        maxLength: 1000,
        maxItems: 2,
      },
      {
        id: 'threshold',
        type: 'number',
        label: 'Strictness',
        required: false,
        defaultValue: 2,
        tooltip:
          'Strictness on a 0–6 scale. Lower values are stricter — the judge flags anything that hints at a violation. Higher values are more lenient — only clear, unambiguous violations are flagged.',
        min: 0,
        max: 6,
        step: 2,
      },
    ],
    status: 'Available',
    description: 'Detect violations of a rule you define, using an LLM as the judge.',
    usageNote:
      "Judge model calls consume Agent units the same way the agent's own LLM calls do. Apply selectively to keep cost predictable, and choose the judge model with cost in mind — rates vary by model.",
    guardrailStages: {
      Agent: ['PreExecution', 'PostExecution'],
      Llm: ['PreExecution', 'PostExecution'],
      Tool: ['PreExecution', 'PostExecution'],
    },
    isByogSubscription: false,
  },
  {
    validator: 'acme_toxicity',
    displayName: 'Acme Toxicity Filter',
    allowedScopes: ['Llm', 'Tool'],
    parameters: [
      {
        id: 'sensitivity',
        type: 'enum',
        label: 'Sensitivity',
        required: true,
        defaultValue: 'medium',
        tooltip: 'How aggressively Acme flags borderline content.',
        options: ['low', 'medium', 'high'],
        optionLabels: {
          low: 'Low',
          medium: 'Medium',
          high: 'High',
        },
      },
      {
        id: 'blockedTerms',
        type: 'text-list',
        label: 'Blocked terms',
        required: false,
        defaultValue: [],
        maxLength: 120,
        maxItems: 50,
      },
    ],
    status: 'Available',
    description: 'Acme Security toxicity classification.',
    byoValidatorName: 'acme-toxicity-v2',
    byoConnectorName: 'Acme Security',
    byoConnectorKey: 'uipath-acme-security',
    byoGuardrailConnectionId: '0f4c1e2a-6c31-4c07-9f2b-2c9a5d3e77b1',
    byoConfigurationId: 'b2ad9f18-5f7f-4a1d-8f2e-8a0d6c1f3b44',
    folderKey: '6b6b3f21-2d34-4a1e-9a77-1f7c0e6d5c92',
    guardrailStages: {
      Llm: ['PreExecution'],
      Tool: ['PreExecution', 'PostExecution'],
    },
    isByogSubscription: true,
  },
  {
    validator: 'acme_pii',
    displayName: 'acme-pii-detector',
    allowedScopes: ['Agent', 'Llm', 'Tool'],
    parameters: [],
    status: 'Disabled',
    byoValidatorName: 'acme-pii-detector',
    byoGuardrailConnectionId: 'd41d8cd9-8f00-4b20-a204-9800998ecf84',
    byoConfigurationId: '3f2504e0-4f89-41d3-9a0c-0305e82c3301',
    guardrailStages: {
      Agent: ['PreExecution', 'PostExecution'],
      Llm: ['PreExecution', 'PostExecution'],
      Tool: ['PreExecution', 'PostExecution'],
    },
    isByogSubscription: true,
  },
  {
    validator: 'pii_detection',
    displayName: 'Acme PII (third party)',
    allowedScopes: ['Llm'],
    parameters: [
      {
        id: 'entities',
        type: 'enum-list',
        label: 'Acme entity set',
        required: true,
        defaultValue: ['Email'],
        options: ['Email', 'Person'],
      },
    ],
    status: 'Available',
    description: 'Acme Security PII classification.',
    byoValidatorName: 'acme-pii-v1',
    byoConnectorName: 'Acme Security',
    byoGuardrailConnectionId: '0f4c1e2a-6c31-4c07-9f2b-2c9a5d3e77b1',
    isByogSubscription: true,
  },
];
