export default {
  overview: 'Overview',
  accordion: 'Accordion',
  'ai-panel': 'AI panel',
  alert: 'Alert',
  'alert-popup': 'Alert popup',
  badge: 'Badge',
  breadcrumb: 'Breadcrumb',
  button: 'Button',
  card: 'Card',
  checkbox: 'Checkbox',
  chip: 'Chip',
  'coach-mark': 'Coach mark',
  combobox: 'Combobox',
  'data-grid': 'Data grid',
  'date-picker': 'Date picker',
  drawer: 'Drawer',
  dropdown: 'Dropdown',
  'global-header': 'Global header',
  'icon-button': 'Icon button',
  'inline-text-editor': 'Inline text editor',
  link: 'Link',
  list: 'List',
  menu: 'Menu',
  modal: 'Modal',
  node: 'Node',
  notifications: 'Notifications',
  'page-header': 'Page header',
  'page-layout': 'Page layout',
  panel: 'Panel',
  'people-picker': 'People picker',
  popover: 'Popover',
  'portal-page-loader': 'Portal page loader',
  'progress-bar': 'Progress bar',
  'progress-spinner': 'Progress spinner',
  'radio-button': 'Radio button',
  'rich-text-editor': 'Rich-text editor',
  'side-nav': 'Side nav',
  'skeleton-loader': 'Skeleton loader',
  slot: 'Slot',
  'sub-header': 'Sub header',
  tabs: 'Tabs',
  'text-input': 'Text input',
  toast: 'Toast',
  'toggle-switch': 'Toggle switch',
  tooltip: 'Tooltip',
  'waffle-menu': 'Waffle menu',
};
