pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1100-110F --output-file=NotoSansKR-Regular.0.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1110-111F --output-file=NotoSansKR-Regular.1.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1120-112F --output-file=NotoSansKR-Regular.2.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1130-113F --output-file=NotoSansKR-Regular.3.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1140-114F --output-file=NotoSansKR-Regular.4.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1150-115F --output-file=NotoSansKR-Regular.5.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1160-116F --output-file=NotoSansKR-Regular.6.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1170-117F --output-file=NotoSansKR-Regular.7.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1180-118F --output-file=NotoSansKR-Regular.8.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+1190-119F --output-file=NotoSansKR-Regular.9.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+11A0-11AF --output-file=NotoSansKR-Regular.A.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+11B0-11BF --output-file=NotoSansKR-Regular.B.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+11C0-11CF --output-file=NotoSansKR-Regular.C.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+11D0-11DF --output-file=NotoSansKR-Regular.D.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+11E0-11EF --output-file=NotoSansKR-Regular.E.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+11F0-11FF --output-file=NotoSansKR-Regular.F.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+A960-A96F --output-file=NotoSansKR-Regular.X-A.0.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+A970-A97F --output-file=NotoSansKR-Regular.X-A.1.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+D7B0-D7BF --output-file=NotoSansKR-Regular.X-B.0.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+D7C0-D7CF --output-file=NotoSansKR-Regular.X-B.1.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+D7D0-D7DF --output-file=NotoSansKR-Regular.X-B.2.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+D7E0-D7EF --output-file=NotoSansKR-Regular.X-B.3.otf
pyftsubset .\NotoSansKR-Regular.otf --unicodes=U+D7F0-D7FF --output-file=NotoSansKR-Regular.X-B.4.otf

