export enum AutopilotChatMode {
    Closed = 'closed',
    SideBySide = 'side-by-side',
    FullScreen = 'full-screen',
    Embedded = 'embedded',
}

export enum AutopilotChatAccordionPosition {
    Left = 'left',
    Right = 'right',
}

export enum AutopilotChatFileType {
    Word = 'Word',
    PowerPoint = 'PowerPoint',
    File = 'File',
}

export interface AutopilotChatFileInfo {
    name: string;
    type: string;
    size: number;
    lastModified: number;
    content: {
        text: string | null;
        binary: Uint8Array | null;
        base64: string | null;
    };
}

/**
 * Represents the model info for the Autopilot Chat system.
 *
 * @property id - Unique identifier for the model
 * @property name - The name of the model
 * @property icon - The Mui icon of the model (optional)
 * @property description - The description of the model
 */
export interface AutopilotChatModelInfo {
    id: string;
    name: string;
    icon?: string;
    description: string | null;
}

export enum AutopilotChatRole {
    User = 'user',
    Assistant = 'assistant',
}

/**
 * Represents a message in the Autopilot Chat system.
 *
 * @property id - Unique identifier for the message. Automatically generated by the chat service if not provided.
 * @property content - The text content of the message.
 * @property created_at - Timestamp when the message was created (generated by the chat service for requests)
 * @property role - Indicates whether the message is from the user or assistant. Set automatically to
 *                  AutopilotChatRole.User for sendRequest and AutopilotChatRole.Assistant for sendResponse.
 * @property widget - The renderer to use for displaying this message.
 * @property attachments - Optional files attached to the message.
 * @property contentParts - Optional content parts for citation support (new format)
 * @property hijacked - Flag set by the chat service when an event is intercepted and the interceptor returns true
 * @property fakeStream - Temporary flag used to simulate streaming for a complete message (will be ignored for requests)
 * @property stream - Flag used to stream a chunk (will be ignored for requests)
 * @property done - Flag to determine if the message is the last chunk of a streaming response
 * @property actions - Additional actions on top of DefaultAutopilotChatResponseAction (for responses)
 *           and DefaultAutopilotChatRequestAction (for requests)
 * @property feedback - Feedback for the message (thumbs up or thumbs down)
 * @property groupId - Optional group ID for the message (used to group messages together)
 * @property meta - Optional metadata for the message (additional information about the message)
 * @property toCopy - Optional string to copy when the message is copied
 * @property shouldWaitForMoreMessages - Optional flag to indicate if the chat service should wait for more messages
 */
export interface AutopilotChatMessage {
    id: string;
    content: string;
    created_at: string;
    role: AutopilotChatRole;
    widget: string;
    attachments?: AutopilotChatFileInfo[];
    contentParts?: ContentPart[];
    hijacked?: boolean;
    fakeStream?: boolean;
    stream?: boolean;
    done?: boolean;
    actions?: AutopilotChatMessageAction[];
    feedback?: {
        isPositive: boolean;
    };
    groupId?: string;
    meta?: any;
    toCopy?: string;
    shouldWaitForMoreMessages?: boolean;
}

export interface AutopilotChatPrompt extends Pick<AutopilotChatMessage, 'content' | 'attachments'> {}

/**
 * Represents a message renderer for the Autopilot Chat system.
 *
 * @property name - The name of the renderer
 * @property render - The function to render the message
 *
 * @returns void or a function to clean up the message renderer
 */
export interface AutopilotChatMessageRenderer {
    name: string;
    render: (container: HTMLElement, message: AutopilotChatMessage) => void | (() => void);
}

/**
 * Enum representing the various events that can occur in the Autopilot Chat system.
 * These events are used for communication between components and for event handling.
 *
 * @enum {string}
 * @property {string} Error - Emitted when an error occurs in the chat system
 * @property {string} NewChat - Emitted when a new chat session is started
 * @property {string} ModeChange - Emitted when the chat mode changes (e.g., from normal to full-screen)
 * @property {string} SetPrompt - Emitted when the chat prompt is set or changed
 * @property {string} Request - Emitted when a user sends a message request
 * @property {string} Response - Emitted when the assistant sends a response
 * @property {string} StopResponse - Emitted when a response is manually stopped
 * @property {string} SetFirstRunExperience - Emitted when the first run experience is configured
 * @property {string} SetDisabledFeatures - Emitted when disabled features are configured
 * @property {string} SetOverrideLabels - Emitted when override labels are configured
 * @property {string} Open - Emitted when the chat is opened
 * @property {string} Close - Emitted when the chat is closed
 * @property {string} SendChunk - Emitted when a chunk of a streaming response is sent
 * @property {string} SetConversation - Emitted when the conversation is set
 * @property {string} SetHistory - Emitted when the history is set
 * @property {string} DeleteConversation - Emitted when a conversation is deleted from the history list
 * @property {string} OpenConversation - Emitted when a conversation is opened (clicked on in the history list)
 * @property {string} Feedback - Emitted when a feedback is sent (thumbs up or thumbs down)
 * @property {string} Copy - Emitted when a message is copied
 * @property {string} SetDefaultLoadingMessages - Emitted when default loading messages are set
 * @property {string} SetLoadingMessage - Emitted when a loading message is set
 * @property {string} SetModels - Emitted when the models are set
 * @property {string} SetSelectedModel - Emitted when the selected model is set
 * @property {string} ConversationLoadMore - Emitted when the conversation load more is triggered
 * @property {string} Attachments - Emitted when the attachments are set in the prompt
 */
export enum AutopilotChatEvent {
    Error = 'error',
    NewChat = 'newChat',
    ModeChange = 'modeChange',
    SetPrompt = 'setPrompt',
    Request = 'request',
    Response = 'response',
    StopResponse = 'stopResponse',
    SetDefaultLoadingMessages = 'setDefaultLoadingMessages',
    SetLoadingMessage = 'setLoadingMessage',
    SetFirstRunExperience = 'setFirstRunExperience',
    SetDisabledFeatures = 'setDisabledFeatures',
    SetOverrideLabels = 'setOverrideLabels',
    Open = 'open',
    Close = 'close',
    SendChunk = 'sendChunk',
    SetConversation = 'setConversation',
    SetHistory = 'setHistory',
    DeleteConversation = 'deleteConversation',
    OpenConversation = 'openConversation',
    Feedback = 'feedback',
    Copy = 'copy',
    SetModels = 'setModels',
    SetSelectedModel = 'setSelectedModel',
    ConversationLoadMore = 'conversationLoadMore',
    Attachments = 'attachments',
    InputStream = 'inputStream',
    OutputStream = 'outputStream',
}

/**
 * Enum representing the various interceptable events that can occur in the Autopilot Chat system.
 * These events are used for intercepting and preventing default handling of events.
 *
 * @enum {string}
 * @property {string} Request - Emitted when a user sends a message request
 */
export enum AutopilotChatInterceptableEvent {
    Request = AutopilotChatEvent.Request,
}

/**
 * Enum representing the various internal events that can occur in the Autopilot Chat system.
 * These events are used for communication between components and for event handling.
 *
 * @enum {string}
 * @property {string} ChatResize - Emitted when the chat is resized
 * @property {string} ScrollToBottom - Emitted when the chat is scrolled to the bottom
 * @property {string} ToggleHistory - Emitted when the history is opened
 * @property {string} ToggleSettings - Emitted when the settings is opened
 * @property {string} UseLocalHistory - Emitted when the chat uses local history
 * @property {string} SetAllowedAttachments - Emitted when the allowed attachments are set
 * @property {string} ToggleAutoScroll - Emitted when the auto scroll is toggled
 * @property {string} SetIsLoadingMoreMessages - Emitted when the is loading more messages is set
 * @property {string} SetShowLoading - Emitted when the show loading is set
 * @property {string} ShouldShowLoadingMoreMessages - Emitted when loading more messages should be shown
 * @property {string} PrependOlderMessages - Emitted when older messages are prepended to the conversation
 * @property {string} ShowLoadingState - Emitted when the loading state should be shown
 * @property {string} SetSuggestions - Emitted when the suggestions are set
 */
export enum AutopilotChatInternalEvent {
    ChatResize = 'chatResize',
    ScrollToBottom = 'scrollToBottom',
    ToggleHistory = 'toggleHistory',
    ToggleSettings = 'toggleSettings',
    UseLocalHistory = 'useLocalHistory',
    SetAllowedAttachments = 'setAllowedAttachments',
    ToggleAutoScroll = 'toggleAutoScroll',
    SetIsLoadingMoreMessages = 'setIsLoadingMoreMessages',
    SetShowLoading = 'setShowLoading',
    ShouldShowLoadingMoreMessages = 'shouldShowLoadingMoreMessages',
    PrependOlderMessages = 'prependOlderMessages',
    ShowLoadingState = 'showLoadingState',
    SetSuggestions = 'setSuggestions',
}

export type AutopilotChatEventHandler<T = any> = (data?: T) => void;

/**
 * @returns true if the event is hijacked by an interceptor
 * @returns void if the event is not hijacked
 * @returns a promise that resolves to true if the event is hijacked
 */
export type AutopilotChatEventInterceptor<T = any> = (data?: T) => boolean | Promise<boolean> | void;

/**
 * Represents a suggestion for the Autopilot Chat system.
 *
 * @property label - The label of the suggestion
 * @property prompt - The prompt of the suggestion
 */
export interface AutopilotChatSuggestion {
    label: string;
    prompt: string;
}

/**
 * Represents a content part in the Autopilot Chat system.
 *
 * @property text - The text content of this part
 * @property citations - The citations that apply to this text
 */
export interface ContentPart {
    text?: string;
    citations?: Array<UrlCitation | PdfCitation>;
}

/**
 * Represents a content part chunk for streaming in the Autopilot Chat system.
 *
 * @property index - The index of the content part this chunk belongs to
 * @property text - The text to append to the content part
 * @property citation - A citation to add to the content part
 */
export interface ContentPartChunk {
    index: number;
    text?: string;
    citation?: UrlCitation | PdfCitation;
}

/**
 * Base citation interface for the Autopilot Chat system.
 *
 * @property id - Unique identifier for the citation
 * @property title - The title of the citation
 */
export interface Citation {
    id: number;
    title: string;
}

/**
 * URL citation that extends the base Citation interface.
 *
 * @property url - The URL of the citation
 */
export interface UrlCitation extends Citation {
    url: string;
}

/**
 * PDF citation that extends the base Citation interface.
 *
 * @property download_url - The URL to download the PDF
 * @property page_number - The page number in the PDF
 */
export interface PdfCitation extends Citation {
    download_url: string;
    page_number: number;
}

/**
 * Represents the disabled features of the Autopilot Chat system.
 *
 * @property resize - Whether the chat can be resized (has the resize handle)
 * @property fullScreen - Whether the chat has the full screen button
 * @property attachments - Whether the chat has the attachments button
 * @property history - Whether the chat has the history button
 * @property header - Whether the chat has the header
 * @property footer - Whether the chat has the footer
 * @property preview - Whether the chat has the preview badge
 * @property close - Whether the chat has the close button
 * @property newChat - Whether the chat has the new chat button
 * @property settings - Whether the chat has the settings button
 * @property audio - Whether the chat has realtime audio enabled
 * @property feedback - Whether the chat has the feedback button
 */
export interface AutopilotChatDisabledFeatures {
    resize?: boolean;
    fullScreen?: boolean;
    attachments?: boolean;
    history?: boolean;
    header?: boolean;
    footer?: boolean;
    preview?: boolean;
    close?: boolean;
    newChat?: boolean;
    settings?: boolean;
    audio?: boolean;
    feedback?: boolean;
}

/**
 * Represents a set of override labels for the Autopilot chat system.
 *
 * @property inputPlaceholder - The override label for input placeholder
 * @property footerDisclaimer - The override label for footer disclaimer
 * @property title - The override label for title
 */
export interface AutopilotChatOverrideLabels {
    inputPlaceholder?: string;
    footerDisclaimer?: string;
    title?: string;
}

/**
 * Represents the various pre-hook actions that can occur in the Autopilot Chat system.
 * These actions are used to trigger before the user action (UI interaction) of the chat.
 *
 * @enum {string}
 * @property {string} NewChat - Emitted when the user attemps to start a new chat
 * @property {string} ToggleHistory - Emitted when the user attemps to toggle the history
 * @property {string} ToggleSettings - Emitted when the user attemps to toggle the settings
 * @property {string} ToggleChat - Emitted when the user attemps to toggle the chat
 * @property {string} CloseChat - Emitted when the user attemps to close the chat
 * @property {string} CitationClick - Emitted when the user clicks on a citation
 */
export enum AutopilotChatPreHookAction {
    NewChat = 'new-chat',
    ToggleHistory = 'toggle-history',
    ToggleSettings = 'toggle-settings',
    ToggleChat = 'toggle-chat',
    CloseChat = 'close-chat',
    CitationClick = 'citation-click',
}

/**
 * Represents the configuration for the Autopilot Chat system.
 *
 * @property mode - The mode of the chat
 * @property embeddedContainer - The container to embed the chat in
 * @property disabledFeatures - The disabled features of the chat
 * @property overrideLabels - The override labels of the chat
 * @property firstRunExperience - The first run experience of the chat
 * @property useLocalHistory - Whether the chat uses indexdb to store history
 * @property allowedAttachments - The allowed attachments of the chat
 * @property models - The models of the chat
 * @property selectedModelId - The selected model ID of the chat
 * @property preHooks - The hooks that trigger before the user action (UI interaction) of the chat.
 *                      Hooks expose current data for the action **before** the state change is attempted.
 * @property paginatedMessages - Flag to determine if the chat conversation is paginated
 * @property settingsRenderer - The renderer for the settings page. This will be used to render the settings page in the chat.
 */
export interface AutopilotChatConfiguration {
    mode: AutopilotChatMode;
    embeddedContainer?: HTMLElement;
    disabledFeatures?: AutopilotChatDisabledFeatures;
    overrideLabels?: AutopilotChatOverrideLabels;
    firstRunExperience?: {
        title: string;
        description: string;
        suggestions?: AutopilotChatSuggestion[];
        sendOnClick?: boolean;
    };
    useLocalHistory?: boolean;
    allowedAttachments?: AutopilotChatAllowedAttachments;
    models?: AutopilotChatModelInfo[];
    selectedModel?: AutopilotChatModelInfo;
    preHooks?: Partial<Record<AutopilotChatPreHookAction, (data?: any) => Promise<boolean>>>;
    paginatedMessages?: boolean;
    settingsRenderer?: (container: HTMLElement) => void;
}

/**
 * Represents a history item for the Autopilot Chat system.
 *
 * @property id - The id of the history item
 * @property name - The name of the history item
 * @property timestamp - The timestamp of the history item
 */
export interface AutopilotChatHistory {
    id: string;
    name: string;
    timestamp: string;
}

/**
 * Represents an action for a message in the Autopilot Chat.
 *
 * @property name - The name of the action
 * @property label - The label of the action
 * @property icon - The icon of the action
 * @property showInOverflow - Whether the action should be shown in the overflow menu instead of the main toolbar
 * @property disabled - Whether the action should be disabled (useful for feedback)
 * @property eventName - The event name to emit when the action is clicked
 * @property details - Additional details for the action
 */
export interface AutopilotChatMessageAction {
    name: string;
    label: string;
    icon?: string;
    showInOverflow?: boolean;
    disabled?: boolean;
    eventName?: string;
    details?: Record<string, any>;
}

/**
 * Represents a payload for an action in the Autopilot Chat.
 *
 * @property action - The action that was triggered
 * @property group - The group of messages that the action is associated with
 * @property message - The last message that the action is associated with.
 */
export interface AutopilotChatActionPayload {
    action: AutopilotChatMessageAction;
    message: AutopilotChatMessage;
    group: AutopilotChatMessage[];
}

/**
 * Represents the allowed attachments for the Autopilot Chat system.
 *
 * @property types - An object mapping MIME types to arrays of file extensions
 *   Example: { 'text/csv': ['.csv'], 'application/json': ['.json'] }
 * @property maxSize - The maximum file size in bytes for attachments
 * @property maxCount - The maximum number of attachments allowed per message
 * @property multiple - Whether the chat allows multiple attachments per message
 */
export interface AutopilotChatAllowedAttachments {
    multiple: boolean;
    types: {
        [key: string]: string[];
    };
    maxSize: number;
    maxCount?: number;
}

/**
 * Input stream event data.
 */
export interface AutopilotChatInputStreamEvent {
    /**
     * If set, indicates that an user input activity is starting.
     */
    activityStart?: AutopilotChatInputStreamActivityStart;

    /**
     * If set, indicates that an user input activity has ended.
     */
    activityEnd?: AutopilotChatInputStreamActivityEnd;

    /**
     * If set, contains input media stream chunks.
     */
    mediaChunks?: AutopilotChatInputStreamMediaChunk[];
}

/**
 * Arguments for an input activity start event. An activity start event must be sent before sending media chunks. An
 * activity end event should be sent after all media chunks have been sent.
 */
export interface AutopilotChatInputStreamActivityStart {
    /**
     * Indicates whether automatic activity detection is enabled for this input stream activity. If enabled,
     * continuously send input media chunks and the LLM will decide when to respond and multiple turns will be taken
     * within the single input activity. If not enabled, the LLM responds when the end activity signal is sent and
     * another start activity needs to be sent to start a new turn.
     */
    automaticActivityDetectionEnabled?: boolean;
}

/**
 * Arguments for an input activity end event.
 */
export interface AutopilotChatInputStreamActivityEnd {
    /**
     * The number following the sequenceNumber of the last media chunk sent in the activity that has ended. This value
     * can be used to verify that all input data messages have been received. TODO: this property will be removed at
     * some point, it is currently used to work around some threading issues in the Agent's service.
     */
    sequenceNumber: number;
}

/**
 * Arguments for an input media chunk event.
 */
export interface AutopilotChatInputStreamMediaChunk extends AutopilotChatMediaChunk {
}

/**
 * Arguments for output stream event.
 */
export interface AutopilotChatOutputStreamEvent {
    /**
     * If set, contains output media stream chunks.
     */
    mediaChunks?: AutopilotChatOutputStreamMediaChunk[];

    /**
     * If set (it will be true), indicates that the LLM output was interrupted by user input. This event will only be
     * generated when automaticActivityDetectionEnabled is set to true in the activity start event.
     */
    interrupted?: boolean;

    /**
     * If set (it will be true), indicates that the LLM has finished generating output in response to an user input. When
     * automaticActivityDetectionEnabled is set, this can occur multiple times during the input activity, otherwise it will
     * occur once, after activity end is sent. If the model was interrupted, generation complete is not sent.
     */
    generationComplete?: boolean;

    /**
     * If set (it will be true), indicates that the turn as completed and the model will generate no more output until a
     * new turn is started by user input. When model assumes realtime playback there will be delay between
     * generation complete and turn complete that is caused by model waiting for playback to finish.
     */
    turnComplete?: boolean;
}

/**
 * Arguments for an output media chunk event.
 */
export interface AutopilotChatOutputStreamMediaChunk extends AutopilotChatMediaChunk {
}

/**
 * Media chunks used for input and output streams.
 */
export interface AutopilotChatMediaChunk {
    /**
     * Sequence of the chunk in the stream. TODO: this property will be removed at some point, it is currently used to
     * work around some threading issues in the Agent's service.
     */
    sequenceNumber: number;
    /**
     * Mime type of the data.
     */
    mimeType: string;
    /**
     * Base64 encoded chunk of data.
     */
    data: string;
}
