export enum AutopilotChatMode {
    Closed = 'closed',
    SideBySide = 'side-by-side',
    FullScreen = 'full-screen',
}

export enum AutopilotChatAccordionPosition {
    Left = 'left',
    Right = 'right',
}

export enum AutopilotChatFileType {
    Word = 'Word',
    PowerPoint = 'PowerPoint',
    File = 'File',
}

export interface AutopilotChatFileInfo {
    name: string;
    type: string;
    size: number;
    lastModified: number;
    content: {
        text: string | null;
        binary: Uint8Array | null;
        base64: string | null;
    };
    icon: string;
    friendlyType: AutopilotChatFileType;
}

export enum AutopilotChatRole {
    User = 'user',
    Assistant = 'assistant',
}

/**
 * Represents a message in the Autopilot Chat system.
 *
 * @property id - Unique identifier for the message. Automatically generated by the chat service if not provided.
 * @property content - The text content of the message.
 * @property created_at - Timestamp when the message was created (generated by the chat service for requests)
 * @property role - Indicates whether the message is from the user or assistant. Set automatically to
 *                  AutopilotChatRole.User for sendRequest and AutopilotChatRole.Assistant for sendResponse.
 * @property widget - The renderer to use for displaying this message.
 * @property attachments - Optional files attached to the message.
 * @property hijacked - Flag set by the chat service when an event is intercepted and the interceptor returns true
 * @property fakeStream - Temporary flag used to simulate streaming for a complete message (will be ignored for requests)
 * @property stream - Flag used to stream a chunk (will be ignored for requests)
 * @property done - Flag to determine if the message is the last chunk of a streaming response
 * @property actions - Additional actions on top of DefaultAutopilotChatResponseAction (for responses)
 *           and DefaultAutopilotChatRequestAction (for requests)
 * @property feedback - Feedback for the message (thumbs up or thumbs down)
 * @property meta - Optional metadata for the message (additional information about the message)
 */
export interface AutopilotChatMessage {
    id: string;
    content: string;
    created_at: string;
    role: AutopilotChatRole;
    widget: string;
    attachments?: AutopilotChatFileInfo[];
    hijacked?: boolean;
    fakeStream?: boolean;
    stream?: boolean;
    done?: boolean;
    actions?: AutopilotChatMessageAction[];
    feedback?: {
        isPositive: boolean;
    };
    meta?: any;
}

export interface AutopilotChatPrompt extends Pick<AutopilotChatMessage, 'content' | 'attachments'> {}

/**
 * Represents a message renderer for the Autopilot Chat system.
 *
 * @property name - The name of the renderer
 * @property render - The function to render the message
 *
 * @returns void or a function to clean up the message renderer
 */
export interface AutopilotChatMessageRenderer {
    name: string;
    render: (container: HTMLElement, message: AutopilotChatMessage) => void | (() => void);
}

/**
 * Enum representing the various events that can occur in the Autopilot Chat system.
 * These events are used for communication between components and for event handling.
 *
 * @enum {string}
 * @property {string} Error - Emitted when an error occurs in the chat system
 * @property {string} NewChat - Emitted when a new chat session is started
 * @property {string} ModeChange - Emitted when the chat mode changes (e.g., from normal to full-screen)
 * @property {string} SetPrompt - Emitted when the chat prompt is set or changed
 * @property {string} Request - Emitted when a user sends a message request
 * @property {string} Response - Emitted when the assistant sends a response
 * @property {string} StopResponse - Emitted when a response is manually stopped
 * @property {string} SetFirstRunExperience - Emitted when the first run experience is configured
 * @property {string} SetDisabledFeatures - Emitted when disabled features are configured
 * @property {string} Open - Emitted when the chat is opened
 * @property {string} Close - Emitted when the chat is closed
 * @property {string} SendChunk - Emitted when a chunk of a streaming response is sent
 * @property {string} SetConversation - Emitted when the conversation is set
 * @property {string} SetHistory - Emitted when the history is set
 * @property {string} DeleteConversation - Emitted when a conversation is deleted from the history list
 * @property {string} OpenConversation - Emitted when a conversation is opened (clicked on in the history list)
 * @property {string} Feedback - Emitted when a feedback is sent (thumbs up or thumbs down)
 * @property {string} Copy - Emitted when a message is copied
 */
export enum AutopilotChatEvent {
    Error = 'error',
    NewChat = 'newChat',
    ModeChange = 'modeChange',
    SetPrompt = 'setPrompt',
    Request = 'request',
    Response = 'response',
    StopResponse = 'stopResponse',
    SetFirstRunExperience = 'setFirstRunExperience',
    SetDisabledFeatures = 'setDisabledFeatures',
    Open = 'open',
    Close = 'close',
    SendChunk = 'sendChunk',
    SetConversation = 'setConversation',
    SetHistory = 'setHistory',
    DeleteConversation = 'deleteConversation',
    OpenConversation = 'openConversation',
    Feedback = 'feedback',
    Copy = 'copy',
}

/**
 * Enum representing the various interceptable events that can occur in the Autopilot Chat system.
 * These events are used for intercepting and preventing default handling of events.
 *
 * @enum {string}
 * @property {string} Request - Emitted when a user sends a message request
 */
export enum AutopilotChatInterceptableEvent {
    Request = AutopilotChatEvent.Request,
}

/**
 * Enum representing the various internal events that can occur in the Autopilot Chat system.
 * These events are used for communication between components and for event handling.
 *
 * @enum {string}
 * @property {string} ChatResize - Emitted when the chat is resized
 * @property {string} ScrollToBottom - Emitted when the chat is scrolled to the bottom
 * @property {string} OpenHistory - Emitted when the history is opened
 * @property {string} CloseHistory - Emitted when the history is closed
 * @property {string} UseLocalHistory - Emitted when the chat uses local history
 */
export enum AutopilotChatInternalEvent {
    ChatResize = 'chatResize',
    ScrollToBottom = 'scrollToBottom',
    ToggleHistory = 'toggleHistory',
    UseLocalHistory = 'useLocalHistory',
}

export type AutopilotChatEventHandler<T = any> = (data?: T) => void;

/**
 * @returns true if the event is hijacked by an interceptor
 * @returns void if the event is not hijacked
 * @returns a promise that resolves to true if the event is hijacked
 */
export type AutopilotChatEventInterceptor<T = any> = (data?: T) => boolean | Promise<boolean> | void;

/**
 * Represents a suggestion for the Autopilot Chat system.
 *
 * @property label - The label of the suggestion
 * @property prompt - The prompt of the suggestion
 */
export interface AutopilotChatSuggestion {
    label: string;
    prompt: string;
}

/**
 * Represents the disabled features of the Autopilot Chat system.
 *
 * @property resize - Whether the chat can be resized (has the resize handle)
 * @property fullScreen - Whether the chat has the full screen button
 * @property attachments - Whether the chat has the attachments button
 * @property history - Whether the chat has the history button
 */
export interface AutopilotChatDisabledFeatures {
    resize?: boolean;
    fullScreen?: boolean;
    attachments?: boolean;
    history?: boolean;
}

/**
 * Represents the configuration for the Autopilot Chat system.
 *
 * @property mode - The mode of the chat
 * @property disabledFeatures - The disabled features of the chat
 * @property firstRunExperience - The first run experience of the chat
 * @property useLocalHistory - Whether the chat uses indexdb to store history
 */
export interface AutopilotChatConfiguration {
    mode: AutopilotChatMode;
    disabledFeatures?: AutopilotChatDisabledFeatures;
    firstRunExperience?: {
        title: string;
        description: string;
        suggestions?: AutopilotChatSuggestion[];
    };
    useLocalHistory?: boolean;
}

/**
 * Represents a history item for the Autopilot Chat system.
 *
 * @property id - The id of the history item
 * @property name - The name of the history item
 * @property timestamp - The timestamp of the history item
 */
export interface AutopilotChatHistory {
    id: string;
    name: string;
    timestamp: string;
}

/**
 * Represents an action for a message in the Autopilot Chat.
 *
 * @property name - The name of the action
 * @property label - The label of the action
 * @property icon - The icon of the action
 * @property showInOverflow - Whether the action should be shown in the overflow menu instead of the main toolbar
 * @property disabled - Whether the action should be disabled (useful for feedback)
 * @property eventName - The event name to emit when the action is clicked
 * @property details - Additional details for the action
 */
export interface AutopilotChatMessageAction {
    name: string;
    label: string;
    icon?: string;
    showInOverflow?: boolean;
    disabled?: boolean;
    eventName?: string;
    details?: Record<string, any>;
}

/**
 * Represents a payload for an action in the Autopilot Chat.
 *
 * @property message - The message that the action is associated with
 * @property action - The action that was triggered
 */
export interface AutopilotChatActionPayload {
    message: AutopilotChatMessage;
    action: AutopilotChatMessageAction;
}
