name: Notify Vertex Component Updates

on:
  push:
    branches: [main]
    paths:
      - "apps/apollo-vertex/registry/**"

permissions:
  contents: read

jobs:
  notify:
    name: Notify changed registry components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Node dependencies
        uses: ./.github/actions/install-node-deps
        with:
          registry-token: ${{ secrets.GH_NPM_REGISTRY_TOKEN }}

      - name: Notify changed components
        env:
          BEFORE_SHA: ${{ github.event.before }}
          AFTER_SHA: ${{ github.event.after }}
          API_KEY: ${{ secrets.VERTEX_TRACKER_API_KEY }}
        run: pnpm notifyUpdates
