// Generated by `pnpm generate:occupants` from registry.json. Don't edit;
// add an occupant item to the registry and rerun it.

import type { OccupantSpec, SurfaceSpec } from "@/lib/composition";
import { contentAreaSurface } from "@/registry/content-area/content-area.surface";
import { pageHeaderSurface } from "@/registry/page-header/page-header.surface";
import { sidePanelSurface } from "@/registry/side-panel/side-panel.surface";
import { activityTimelineOccupant } from "@/registry/activity-timeline/activity-timeline.occupant";
import { EXAMPLES as activityTimelineExamples } from "@/registry/activity-timeline/examples";
import { keyFactsOccupant } from "@/registry/key-facts/key-facts.occupant";
import { EXAMPLES as keyFactsExamples } from "@/registry/key-facts/examples";
import { stageStripOccupant } from "@/registry/stage-strip/stage-strip.occupant";
import { EXAMPLES as stageStripExamples } from "@/registry/stage-strip/examples";

export interface RegisteredOccupantSpec {
  spec: OccupantSpec;
  /** Its example roles: primary, secondary, and stress. */
  examples: readonly string[];
}

/** Every registered surface. */
export const SURFACE_SPECS: readonly SurfaceSpec[] = [
  contentAreaSurface,
  pageHeaderSurface,
  sidePanelSurface,
];

/** Every registered occupant, by name. */
export const OCCUPANT_SPECS: readonly RegisteredOccupantSpec[] = [
  {
    spec: activityTimelineOccupant,
    examples: Object.keys(activityTimelineExamples),
  },
  { spec: keyFactsOccupant, examples: Object.keys(keyFactsExamples) },
  { spec: stageStripOccupant, examples: Object.keys(stageStripExamples) },
];
