// Generated by `pnpm generate:occupants` from registry.json. Don't edit;
// add an occupant item to the registry and rerun it.

import type { OccupantSpec } from "@/lib/composition";
import { activityTimelineOccupant } from "@/registry/activity-timeline/activity-timeline.occupant";
import { EXAMPLES as activityTimelineExamples } from "@/registry/activity-timeline/examples";
import { stageStripOccupant } from "@/registry/stage-strip/stage-strip.occupant";
import { EXAMPLES as stageStripExamples } from "@/registry/stage-strip/examples";

export interface RegisteredOccupantSpec {
  spec: OccupantSpec;
  /** The names of its example views, "stress" included. */
  examples: readonly string[];
}

/** Every registered occupant, by name. */
export const OCCUPANT_SPECS: readonly RegisteredOccupantSpec[] = [
  {
    spec: activityTimelineOccupant,
    examples: Object.keys(activityTimelineExamples),
  },
  { spec: stageStripOccupant, examples: Object.keys(stageStripExamples) },
];
