// Generated by `pnpm generate:occupants` from registry.json. Don't edit;
// add an occupant item to the registry and rerun it.

import { defineOccupant, type RegisteredOccupant } from "@/lib/occupant-entry";
import { ActivityTimeline } from "@/registry/activity-timeline/activity-timeline";
import { activityTimelineOccupant } from "@/registry/activity-timeline/activity-timeline.occupant";
import { EXAMPLES as activityTimelineExamples } from "@/registry/activity-timeline/examples";
import { KeyFacts } from "@/registry/key-facts/key-facts";
import { keyFactsOccupant } from "@/registry/key-facts/key-facts.occupant";
import { EXAMPLES as keyFactsExamples } from "@/registry/key-facts/examples";
import { StageStrip } from "@/registry/stage-strip/stage-strip";
import { stageStripOccupant } from "@/registry/stage-strip/stage-strip.occupant";
import { EXAMPLES as stageStripExamples } from "@/registry/stage-strip/examples";

/** Every registered occupant with its component and example views. */
export const OCCUPANT_REGISTRY: readonly RegisteredOccupant[] = [
  defineOccupant({
    spec: activityTimelineOccupant,
    Component: ActivityTimeline,
    examples: activityTimelineExamples,
  }),
  defineOccupant({
    spec: keyFactsOccupant,
    Component: KeyFacts,
    examples: keyFactsExamples,
  }),
  defineOccupant({
    spec: stageStripOccupant,
    Component: StageStrip,
    examples: stageStripExamples,
  }),
];
